use inc::Module::JSAN::DSL;


name                Joose
version             3.004
	
author              'Nickolay Platonov (aka SamuraiJack) <nplatonov@cpan.org>'
author              'Malte Ubl'
author              'Jeremy Wall'

abstract            'Post modern self-hosting meta object system for JavaScript with support for classes, inheritance, roles, traits, method modifiers and more.'
	
license             bsd
	
	
docs_markup         mmd
