COMPONENTS = {
    
    "Core" : [
        "Joose",
        "Joose.Proto.Empty",
        "Joose.Proto.Object",
        "Joose.Proto.Class",
    
        "Joose.Managed.Property",
        "Joose.Managed.Property.ConflictMarker",
        "Joose.Managed.Property.Requirement",
        "Joose.Managed.Property.Attribute",
        "Joose.Managed.Property.MethodModifier",
        "Joose.Managed.Property.MethodModifier.Override",
        "Joose.Managed.Property.MethodModifier.Put",
        "Joose.Managed.Property.MethodModifier.After",
        "Joose.Managed.Property.MethodModifier.Before",
        "Joose.Managed.Property.MethodModifier.Around",
        "Joose.Managed.Property.MethodModifier.Augment",
        
        "Joose.Managed.PropertySet",
        "Joose.Managed.PropertySet.Mutable",
        
        "Joose.Managed.StemElement.Attributes",
        "Joose.Managed.StemElement.Methods",
        "Joose.Managed.StemElement.Requirements",
        "Joose.Managed.StemElement.MethodModifiers",
        
        "Joose.Managed.PropertySet.Composition",
        "Joose.Managed.Stem",
        "Joose.Managed.Builder",
        "Joose.Managed.Class",
        "Joose.Managed.Role",
                    
        "Joose.Managed.Attribute",
        
        "Joose.Managed.PropertySet.Namespace",
        
        "Joose.Managed.Attribute.Builder",
        "Joose.Managed.My",
        "Joose.Namespace.Able",
        
        "Joose.Managed.Bootstrap",
        
        "Joose.Meta.Object",
        "Joose.Meta.Class",
        "Joose.Meta.Role",
        
        "Joose.Namespace.Keeper",
        "Joose.Namespace.Manager"
    ]
    
}
